# SPDX-FileCopyrightText: 2026 Knitli Inc.
# SPDX-FileContributor: Adam Poulemanos <adam@knit.li>
#
# SPDX-License-Identifier: MIT OR Apache-2.0
# cargo-release workspace configuration
# https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md
allow-branch = ["main"]
shared-version = false
consolidate-commits = true
push-remote = "origin"
push = true
publish = true
